export PATH=/work/shared/users/phd/jl3952/workspace/MLIR_dialect/sparlay/build/bin/:$PATH
export LD_LIBRARY_PATH=/work/shared/users/phd/jl3952/workspace/MLIR_dialect/sparlay/build/lib:$LD_LIBRARY_PATH
# export TENSOR0=/work/shared/users/phd/jl3952/workspace/MLIR_dialect/sparlay/test/Data/tensor46.mtx
# export TENSOR0=/work/shared/users/phd/jl3952/workspace/MLIR_dialect/sparlay/evaluation/dataset/abb313.mtx
export TENSOR0=/work/shared/common/datasets/SuiteSparse_MLIR/abb313_row_major.mtx
# export TENSOR0=/work/shared/common/datasets/SuiteSparse_MLIR/ss1_row_major.mtx
# export TENSOR0=/work/shared/common/datasets/SuiteSparse_MLIR/stomach_row_major.mtx
# export TENSOR0=/work/shared/common/datasets/SuiteSparse_MLIR/scircuit_row_major.mtx
# export TENSOR0=/work/shared/common/datasets/SuiteSparse_MLIR/Hamrle3_row_major.mtx
# export TENSOR0=/work/shared/common/datasets/SuiteSparse_MLIR/Transport_row_major.mtx